### ISSUE TITLE
Update lodash dependency, cause npm audit warns about an issue

### ISSUE THREAD

**Issue by tzahari** [MathieuLoutre/grunt-aws-s3#126]
Please update the lodash dependency

`┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.11                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grunt-aws-s3 [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ grunt-aws-s3 > lodash                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/782                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grunt-aws-s3 [dev]                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ grunt-aws-s3 > lodash                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/577                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
`
Thank you

**Comment by ffflorian** [comment]
ping @MathieuLoutre
