### ISSUE TITLE
Upload 'cwd' does not work

### ISSUE THREAD

**Issue by terryx** [MathieuLoutre/grunt-aws-s3#20]
files: [{
                    expand: true,
                    cwd: 'public/scripts',
                    src: ['public/scripts/*.js'],
                    dest: 'scripts/',
                    params: {
                        ContentEncoding: 'gzip'
                    },
                }]

if i omitted cwd it will upload to s3, but whenever i included it the grunt task just keep running without stopping

**Comment by xsurfing** [comment]
FYI, just in case someone else runs into this... Spent frustrating minutes to get down to the "cwd" issue as well... My conclusion: It does NOT work if you use "expand:false", it DOES with "expand:true".
Maybe that's helping you, Mathieu, checking this out - if you find time. Thx!

**Comment by MathieuLoutre** [comment]
Thanks @xsurfing! Not sure there's a workaround to use `expand:false` but maybe it's worth putting it in the docs clearly. Thanks for the tip :)

**Comment by stevemayhew** [comment]
Hard to workaround, cause it happens before your task is called.   Here's the offending bit in grunt task.js  https://github.com/gruntjs/grunt/blob/master/lib/grunt/task.js#L135

This will report a warning if the condition is detected
https://github.com/MathieuLoutre/grunt-aws-s3/pull/117
