### ISSUE TITLE
question: check s3 dir exists

### ISSUE THREAD

**Issue by peter-mouland** [MathieuLoutre/grunt-aws-s3#41]
I am using this to upload versioned files (ie. function/0.0.1/dist/) and the current upload function will over-write files that already exist. uploading over an existing dir is undesirable for me!

anyway we can use this plug in to check a s3 dir exists before upload?

**Comment by MathieuLoutre** [comment]
Hi @peter-mouland, something like this is in the works thanks to @nickjackson. I've created a new branch which awaits testing. It should be published soon hopefully.

**Comment by MathieuLoutre** [comment]
It's now available in `0.13.0`. Please re-open if you have any trouble.
