### ISSUE TITLE
Move Action

### ISSUE THREAD

**Issue by lylepratt** [MathieuLoutre/grunt-aws-s3#51]
I came here to look up the documentation for a "move" action, but realized that there isn't one. Would it be difficult to add one?

We have a need to move the current files, in a directory we are uploading to, into a versioned "roll back" directory.

**Comment by MathieuLoutre** [comment]
@lylepratt, I've published `0.11.0` which has a copy action. Take it for a test drive if you can and let me know.

**Comment by lylepratt** [comment]
Just updated and added a `copy` action and it's working great. Thanks!

**Comment by MathieuLoutre** [comment]
Awesome! Post an issue if you run into trouble :)
