### ISSUE TITLE
Issue deleting bucket files with suggested policy actions

### ISSUE THREAD

**Issue by charlieanstey** [MathieuLoutre/grunt-aws-s3#60]
I think this is a documentation issue. When setting up the policies for the task, I had trouble with the delete command not working, getting the following error:
```
Running "s3Deploy:staging" (s3Deploy) task
Deleting the content of https://s3-eu-west-1.amazonaws.com/mybucket-name/styles/
Fatal error: Failed to list content of bucket mybucket-name
AccessDenied: Access Denied
```
Through trial and error, and having read @coop182's [blog post on getting started](http://matthewcooper.net/2015/01/30/deploying-client-side-applications-to-s3-with-grunt/), I've ended up with this IAM policy in AWS:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1424411733000",
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::mybucket-name",
        "arn:aws:s3:::mybucket-name/*"
      ]
    }
  ]
}
```
Note the 2 resources with and without the `/*`. After having limited the actions to what your readme said and having added `DeleteObject`, this is what fixed the errors for me. Am I doing something wrong?

**Comment by MathieuLoutre** [comment]
Hi there!

I think you might be right and it's a documentation problem. The info in the README concerning the IAM rights might be a little outdated if you're using some of the new features (Delete, Copy). Having `Action": "s3:*` seems correct.

If this config is working for you, I don't think there's anything wrong with it.

**Comment by charlieanstey** [comment]
Yep that's cool, I've left those permissions in place for now. It would be better to have minimally required permission enabled though..

I don't have time right now but if I get a chance to test, I'll could do a pull request on the docs?

**Comment by MathieuLoutre** [comment]
Yes please! PRs are always welcome, even better if it's docs :)
