### ISSUE TITLE
Use `storageClass: 'REDUCED_REDUNDANCY'`

### ISSUE THREAD

**Issue by SimplGy** [MathieuLoutre/grunt-aws-s3#61]
Hey again Mathieu, been a while!

I was trying to use this option `REDUCED_REDUNDANCY`.

From the AWS docs:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

Tried a few variations of capitalization on the `storageClass` key, but wasn't able to get it to take. Are the options passed through one at a time--so that an option you haven't specifically handled won't get sent to the AWS api, or are they sent through exactly as I type them?

**Comment by MathieuLoutre** [comment]
H there!

I haven't used it myself but in theory if you use the `params` option with the `StorageClass` key, it should be sent along. If it's not, then there might be a bug and I should investigate.

You can see here that the upload object is taking what's in `params`: https://github.com/MathieuLoutre/grunt-aws-s3/blob/master/tasks/aws_s3.js#L692

**Comment by SimplGy** [comment]
Yup, that works great. I forgot `params` is the key to just pass options on to AWS. Thanks!

**Comment by MathieuLoutre** [comment]
No problem! Glad it's working!
