### ISSUE TITLE
action: 'delete' - Fatal error: Failed to list content of bucket <bucket> NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by IainAndrew** [MathieuLoutre/grunt-aws-s3#66]
I have this task working perfectly for uploading, but I can't seem to be able to delete files from my bucket. I get this error when running `grunt aws_s3:clean`:

    Fatal error: Failed to list content of bucket <bucket>
    NoSuchKey: The specified key does not exist.

Here's my task config:

    aws: grunt.file.readJSON('aws-keys.json'),

    aws_s3: {
      options: {
        accessKeyId: '<%= aws.AWSAccessKeyId %>',
        secretAccessKey: '<%= aws.AWSSecretKey %>',
        region: 'eu-west-1',
        uploadConcurrency: 5,
        downloadConcurrency: 5,
        bucket: '<bucket>'
      },
      deploy: {
        files: [{
          expand: true, 
          cwd: 'dist', 
          src: [
            '**/*'
          ], 
          dest: ''
        }]
      },
      clean: {
        options: {
          debug: true
        },
        files: [{
          dest: '/', 
          action: 'delete'
        }]
      }
    }

**Comment by IainAndrew** [comment]
My mistake. I didn't realise having `debug: true` prevented it from performing the action. It also didn't like the fact that `bucket` was set to <bucketname/foldername>, though it worked fine with the deploy task for some reason!

**Comment by MathieuLoutre** [comment]
Sorry for the late reply, entirely missed that notification. It might (certainly) be related to some changes that have been made in `mock-aws-s3` a few weeks ago. It was related to the the naming of the bucket, so it's likely. `debug: true` indeed doesn't perform the action, just does a "dry" run.

Did your bucket string have any characters outside of [a-zA-Z]?

**Comment by IainAndrew** [comment]
My `bucket` string was basically 'bucket-name/directory-name'. The upload task was fine with having a subdirectory in `bucket` but the delete task was not. So I ended up just having `bucket` be the bucket name, and putting the subdirectory as the `dest` of both tasks.

**Comment by MathieuLoutre** [comment]
Interesting, thanks! Must be a weird path calculation in the mock library. I'll have a look.

**Comment by IainAndrew** [comment]
It's a tiny issue really, but thanks for taking a look :)

**Comment by MathieuLoutre** [comment]
The mock library has been updated (but on this module yet) so I'm hoping this issue will be solved! Otherwise, feel free to re-open.
