### ISSUE TITLE
options.access doesn't apply to the copy action

### ISSUE THREAD

**Issue by rayd** [MathieuLoutre/grunt-aws-s3#70]
When I perform a copy action and set options.access to `public-read` the copied files in S3 aren't actually set to use this ACL.

**Comment by MathieuLoutre** [comment]
Ah! That's a good one. Guess it needs to have `ACL: options.access` as part of the function call on L465. Feel like a PR?

**Comment by rayd** [comment]
Certainly -- was in the process of doing it!

**Comment by MathieuLoutre** [comment]
Closed by #71
