### ISSUE TITLE
How do you handle errors?

### ISSUE THREAD

**Issue by heavysixer** [MathieuLoutre/grunt-aws-s3#79]
My application will upload the assets to S3 and then iterate over the html and css files and replace the references to the local assets to the remote assets. I of course want to skip this for any and all assets that were unsuccessfully uploaded. 

Is there a way to get a reference to each file that passed / failed the upload process for use later in the grunt task?

Thanks!
Mark

**Comment by MathieuLoutre** [comment]
Hi there! I'm pretty sure that currently, if there's an errors, the grunt task will fail, which is likely to stop the grunt process altogether. Basically if anything doesn't get uploaded, it will throw. I guess it somehow works out for your use case (I've used the same technique in production without a hitch so far), but if you have a use case for letting errors through and continue uploading, I'd like to hear it :)

**Comment by MathieuLoutre** [comment]
You can get a list of changed files (after the upload is finished) with this: https://github.com/MathieuLoutre/grunt-aws-s3#optionschangedfiles
An array gets attached to the grunt config with the changed files.

**Comment by heavysixer** [comment]
excellent thanks for that @MathieuLoutre.
