### ISSUE TITLE
Bucket not configurable at task level

### ISSUE THREAD

**Issue by AxelDelmas** [MathieuLoutre/grunt-aws-s3#87]
Bucket can only be configured in `options`, which is a problem when one wants to, for example, move files from a bucket to another.

bucket, credential, region, and so on, should IMO be configurable at the task level.

**Comment by AxelDelmas** [comment]
Ahem. Those can be overriden with a task level options object. I should have read grunt doc more carefully. Seems my PR doesn't bring any value (shame you can't delete issues / PR on github).

**Comment by MathieuLoutre** [comment]
No worries, if you're not familiar with how the options work in Grunt, it would have been a legitimate concern. I'll close the issue, but if you have any other questions, don't hesitate.
