### ISSUE TITLE
Add a preprocessor task to generate fixtures for testing

### ISSUE THREAD

**Issue by frankcortes** [MathieuLoutre/grunt-aws-s3#91]
When someone wants to use this library as a dependency **must add 2953 extra files** (915 `river` + 563 `sea` + 1475 `updated`) **that will never use**. Of course, these files are empty fixtures. However, the number of files that an OS can support in a folder isn't infinite, so the high number of files is still relevant. Couldn't you better generate these files as a part of the `test`/`grunt` task?

**Comment by MathieuLoutre** [comment]
That's a very good point. I've been quite bothered about them for a while to be honest. I'd be very happy to take a PR in fact if you have the time. Otherwise I'll look into it whenever I can.

**Comment by frankcortes** [comment]
@MathieuLoutre sure, I will do a PR as soon as possible :+1:

**Comment by MathieuLoutre** [comment]
Closed by #92
