### ISSUE TITLE
CWD ignored in non-debug mode

### ISSUE THREAD

**Issue by Cosrnos** [MathieuLoutre/grunt-aws-s3#95]
Hey guys!

Trying to upload some folders to s3. My folder structure is basically:

```
-/_build
---/files_to_upload
-----/scripts
-------/a.js.gz
-------/b.js.gz
-------/c.js.gz
```

My config is as follows:

```
            options: {
                accessKeyId: 'the_key'
                secretAccessKey: 'the_other_key',
                bucket: 'bucket',
                access: 'public-read',
                gzipRename: 'ext'
            },
            files: [{
                action: 'upload',
                cwd: '_build/files_to_upload/',
                src: ['**/*'],
                dest: '/',
            }]
```

Basically I want everything in files_to_upload to be uploaded relative to the bucket root. When debug mode is enabled, the file names dump out as expected. However once I disable debug mode I immediately get

```
Uploading to https://s3.amazonaws.com/bucket/
Fatal error: Unable to read "scripts/a.js.gz" file (Error code: ENOENT).
```

AFAIK our config is correct, otherwise debug mode would spit something else out. I think something weird is happening internally with file paths...

**EDIT:** Holy crap, total oversight on my part. After re-reading my issue I noticed I had accidentally removed the expand option in the file config. I'll leave my problem description up in case it helps anyone in the future. Sorry for the redundant issue!

On the other hand, I still find it odd that the debug flag would cause it to appear like it's working correctly. Might want to fail on that end for consistency.

**Comment by MathieuLoutre** [comment]
Good shout regarding the debug flag. Did the visual output match what you expected or not? Because `debug` currently skip a lot of the system, it's possible to have inconsistencies. Something to look into I guess (if you had the time to look and the code and do a PR, I'd gladly take it).

Closing for now but feel free to re-open if there's a problem.

**Comment by Cosrnos** [comment]
Yeah if I have time over the weekend I can look into making debug a little more consistent with actual behavior. The debug flag had output the names I expected so it was confusing when I removed the flag and things didn't work :)

**Comment by MathieuLoutre** [comment]
Awesome! No rush as it's not really a breaking bug :)
