### ISSUE TITLE
Question: apply params to only 1 file

### ISSUE THREAD

**Issue by karensg** [MathieuLoutre/grunt-aws-s3#96]
Hi,

I am wondering if it is possible to apply the params to only 1 file. I would like to add different 'Cache-control' headers to my files. Is it possible to apply params based on a pattern?

Cool library, I use it happily for months now :)

**Comment by MathieuLoutre** [comment]
Hi! Right now your best bet would be to upload that file separately and use a file array:

```
files: [
      {expand: true, cwd: 'dist/', src: ['**'], dest: '/'},
      {expand: true, cwd: 'dist/assets', src: ['app.js'], dest: 'assets/', params: {CacheControl: '2000'}},
    ]
```

**Comment by karensg** [comment]
Great, thanks a lot for the suggestion!
I got it working with:
```
{expand: true, cwd: 'dist/', src: ['**', '!index.html'], dest: '/'},
{expand: true, cwd: 'dist/', src: ['index.html'], dest: '/', params: {CacheControl: 'no-cache'}}
```

**Comment by MathieuLoutre** [comment]
Awesome! Good use of the `!` as well ;)
